### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by thefunnyman** [mreuvers/typescript-logging#3]
Hi,

I'm using the latest 0.2.0 release of this lib and i'm getting an error when i run the code described in the 0.2.0 documentation. 

Here's the stacktrace. This is not a browser-based application, so "window" wouldn't be defined.

```
C:\Users\Matt\Documents\VSCodeProjects\api\node_modules\typescript-logging\dist\commonjs\extension\ExtensionHelper.js:22
            window.removeEventListener("message", listener);
            ^

ReferenceError: window is not defined
    at Function.ExtensionHelper.register (C:\Users\Matt\Documents\VSCodeProjects\api\node_modules\typescript-logging\dist\commonjs\extension\ExtensionHelper.js:22:13)
    at Object.<anonymous> (C:\Users\Matt\Documents\VSCodeProjects\api\node_modules\typescript-logging\dist\commonjs\typescript-logging.js:47:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Matt\Documents\VSCodeProjects\api\src\lib\config\logging.js:3:28)
```

**Comment by mreuvers** [comment]
Hello,

Thank you for logging the problem. This needs to be fixed. For context what are you using in this case?

**Comment by thefunnyman** [comment]
Hi @mreuvers!

Please find attached a zip project that demonstrates the bug. For my use case, i'm exposing a hapijs web service.
[typescript-sample.zip](https://github.com/mreuvers/typescript-logging/files/815454/typescript-sample.zip)

**Comment by mreuvers** [comment]
Thank you @thefunnyman , it reproduces for me running it through node as well.
I'll get it fixed today/tomorrow.

**Comment by mreuvers** [comment]
Hello @thefunnyman 

The issue should be fixed, I pushed version 0.2.1 to npm which should be available shortly. Please let me know if the issue has been resolved for you.

**Comment by thefunnyman** [comment]
I can see logs now. thanks so much! I'll open another ticket or explore some of the code myself if i see any other issues.

**Comment by mreuvers** [comment]
No problem. :) If you run into an issue again, please let me know (hopefully not too many though ;)).
