### ISSUE TITLE
Error when calling log functions that are a lower level than the configured log level

### ISSUE THREAD

**Issue by evanplett** [mreuvers/typescript-logging#46]
I get an error whenever I have a log function that is lower than the configured log level.

When I create a logger like this:

```
import {
  Category,
  CategoryLogger,
  CategoryServiceFactory,
  CategoryConfiguration,
  LogLevel
} from 'typescript-logging';


CategoryServiceFactory.setDefaultConfiguration(new CategoryConfiguration(LogLevel.Debug));

export const myLogger = new Category('myLogger');
```

And then use it like this:

```
import {
  myLogger as logger
} from '../log_config';

logger.trace("Some Message);
```

I get the error below. 

Note: if I change the level of the message by changing the function from trace to debug, the error goes away). Also, if I change LogLevel.Debug to LogLevel.Trace, the error goes away. in fact, this happens whenever the "CategoryServiceFactory.setDefaultConfiguration(new CategoryConfiguration(LogLevel.Debug));" is set to a higher log level than the function being called.

**ERROR and Stack Trace:**

(node:903) UnhandledPromiseRejectionWarning: TypeError: category.getCategoryPath is not a function
           at Function.CategoryServiceImpl.getCategoryKey (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/CategoryService.js:152:25)
           at CategoryServiceImpl.createOrGetCategoryState (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/CategoryService.js:120:39)
           at CategoryServiceImpl.getCategorySettings (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/CategoryService.js:44:21)
           at _loop_1 (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js:250:51)
           at CategoryConsoleLoggerImpl.AbstractCategoryLogger._logInternal (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js:284:27)
           at CategoryConsoleLoggerImpl.AbstractCategoryLogger._log (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js:232:27)
           at CategoryConsoleLoggerImpl.AbstractCategoryLogger.trace (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js:142:19)
           at CategoryDelegateLoggerImpl.trace (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/CategoryDelegateLoggerImpl.js:25:37)
           at Category.trace (/tmp/build_44d3b1e8e660550008cf6d748f4beb4b/node_modules/typescript-logging/dist/commonjs/log/category/Category.js:61:35)

**Comment by mreuvers** [comment]
Hello Evan,

I cannot reproduce. Could you please provide a minimum setup using npm to reproduce this?

Thank you.

**Comment by evanplett** [comment]
This was a user error.

I had a line like:

logger.trace("The value of the object is %o", object);

When I changed this line to:

logger.trace("The value of the object is " + object);

the error went away.
